# -*- coding: utf-8 -*-
"""Agarwalwork.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rytcI_JybMoQ02uhuD986zzkxQGq1Zo3
"""

# DATABASE & APTITUDE TESTING MODULE - TANISHA AGGARWAL
# 40% Implementation - Working Code

import sqlite3
import json
import random
from datetime import datetime
from typing import List, Dict, Optional
import hashlib
import pandas as pd

class DatabaseManager:
    """Database management for career counseling system"""

    def __init__(self, db_name='career_counseling.db'):
        self.db_name = db_name
        self.conn = None
        self.cursor = None
        self.connect()
        self.create_tables()

    def connect(self):
        """Establish database connection"""
        self.conn = sqlite3.connect(self.db_name, check_same_thread=False)
        self.cursor = self.conn.cursor()

    def create_tables(self):
        """Create all necessary tables"""

        # Users table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS users (
                user_id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                email TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                full_name TEXT,
                age INTEGER,
                education_level TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Aptitude tests table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS aptitude_tests (
                test_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                test_type TEXT,
                score REAL,
                completed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (user_id)
            )
        ''')

        # Test questions table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS questions (
                question_id INTEGER PRIMARY KEY AUTOINCREMENT,
                category TEXT NOT NULL,
                difficulty TEXT,
                question_text TEXT NOT NULL,
                options TEXT NOT NULL,
                correct_answer INTEGER NOT NULL,
                explanation TEXT
            )
        ''')

        # User responses table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS user_responses (
                response_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                test_id INTEGER,
                question_id INTEGER,
                user_answer INTEGER,
                is_correct BOOLEAN,
                time_taken INTEGER,
                FOREIGN KEY (user_id) REFERENCES users (user_id),
                FOREIGN KEY (test_id) REFERENCES aptitude_tests (test_id),
                FOREIGN KEY (question_id) REFERENCES questions (question_id)
            )
        ''')

        # Career recommendations table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS career_recommendations (
                recommendation_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                career_title TEXT,
                match_percentage REAL,
                reasoning TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (user_id)
            )
        ''')

        # Career profiles table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS career_profiles (
                career_id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL,
                category TEXT,
                description TEXT,
                required_skills TEXT,
                education_requirements TEXT,
                salary_range TEXT,
                growth_prospects TEXT
            )
        ''')

        # Admin Users table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS admin_users (
                admin_id INTEGER PRIMARY KEY AUTOINCREMENT,
                username TEXT UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Activity Logs table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS activity_logs (
                log_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                action TEXT NOT NULL,
                details TEXT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Error Logs table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS error_logs (
                error_id INTEGER PRIMARY KEY AUTOINCREMENT,
                error_message TEXT NOT NULL,
                stack_trace TEXT,
                endpoint TEXT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')

        # Recommendation Feedback table
        self.cursor.execute('''
            CREATE TABLE IF NOT EXISTS recommendation_feedback (
                feedback_id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER,
                recommendation_id INTEGER,
                feedback_type TEXT NOT NULL, 
                details TEXT,
                timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                FOREIGN KEY (user_id) REFERENCES users (user_id),
                FOREIGN KEY (recommendation_id) REFERENCES career_recommendations (recommendation_id)
            )
        ''')

        self.conn.commit()

    def hash_password(self, password: str) -> str:
        """Hash password for security"""
        return hashlib.sha256(password.encode()).hexdigest()

    def add_user(self, username: str, email: str, password: str,
                 full_name: str = None, age: int = None,
                 education_level: str = None) -> int:
        """Add new user to database"""
        try:
            password_hash = self.hash_password(password)
            self.cursor.execute('''
                INSERT INTO users (username, email, password_hash, full_name, age, education_level)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (username, email, password_hash, full_name, age, education_level))
            self.conn.commit()
            return self.cursor.lastrowid
        except sqlite3.IntegrityError as e:
            print(f"Error adding user: {e}")
            return None

    def authenticate_user(self, username: str, password: str) -> Optional[Dict]:
        """Authenticate user login"""
        password_hash = self.hash_password(password)
        self.cursor.execute('''
            SELECT user_id, username, email, full_name
            FROM users
            WHERE username = ? AND password_hash = ?
        ''', (username, password_hash))

        result = self.cursor.fetchone()
        if result:
            self.log_activity(result[0], 'USER_LOGIN', 'User logged in successfully')
            return {
                'user_id': result[0],
                'username': result[1],
                'email': result[2],
                'full_name': result[3]
            }
        return None

    def authenticate_admin(self, username: str, password: str) -> bool:
        """Authenticate an admin login and seed one if missing"""
        self.cursor.execute("SELECT COUNT(*) FROM admin_users")
        if self.cursor.fetchone()[0] == 0:
            self.cursor.execute("INSERT INTO admin_users (username, password_hash) VALUES (?, ?)", 
                                ("admin", self.hash_password("admin123")))
            self.conn.commit()
            
        password_hash = self.hash_password(password)
        self.cursor.execute('SELECT admin_id FROM admin_users WHERE username = ? AND password_hash = ?', (username, password_hash))
        result = self.cursor.fetchone()
        if result:
            self.log_activity(None, 'ADMIN_LOGIN', f'Admin {username} logged in')
            return True
        return False

    def log_activity(self, user_id: Optional[int], action: str, details: str = None):
        """Log a system activity"""
        self.cursor.execute('''
            INSERT INTO activity_logs (user_id, action, details)
            VALUES (?, ?, ?)
        ''', (user_id, action, details))
        self.conn.commit()

    def log_error(self, error_message: str, stack_trace: str = None, endpoint: str = None):
        """Log a system error"""
        self.cursor.execute('''
            INSERT INTO error_logs (error_message, stack_trace, endpoint)
            VALUES (?, ?, ?)
        ''', (error_message, stack_trace, endpoint))
        self.conn.commit()

    def add_recommendation_feedback(self, user_id: int, recommendation_id: int, feedback_type: str, details: str = None):
        """Store user feedback (upvote/downvote) on a recommendation"""
        self.cursor.execute('''
            INSERT INTO recommendation_feedback (user_id, recommendation_id, feedback_type, details)
            VALUES (?, ?, ?, ?)
        ''', (user_id, recommendation_id, feedback_type, details))
        self.conn.commit()
        self.log_activity(user_id, 'SUBMIT_FEEDBACK', f'{feedback_type} on recommendation #{recommendation_id}')

    def get_dashboard_stats(self) -> Dict:
        """Get high-level statistics for Admin Dashboard"""
        self.cursor.execute("SELECT COUNT(*) FROM users")
        total_users = self.cursor.fetchone()[0]
        
        self.cursor.execute("SELECT COUNT(*) FROM aptitude_tests")
        total_tests = self.cursor.fetchone()[0]
        
        self.cursor.execute("SELECT COUNT(*) FROM error_logs")
        total_errors = self.cursor.fetchone()[0]
        
        self.cursor.execute("SELECT test_type, AVG(score) FROM aptitude_tests GROUP BY test_type")
        avg_scores = {row[0]: round(row[1], 2) for row in self.cursor.fetchall()}
        
        return {
            'total_users': total_users,
            'total_tests': total_tests,
            'total_errors': total_errors,
            'avg_scores': avg_scores
        }
        
    def get_recent_activity(self, limit: int = 20) -> List[Dict]:
        """Fetch latest activity logs"""
        self.cursor.execute('''
            SELECT log_id, user_id, action, details, timestamp
            FROM activity_logs ORDER BY timestamp DESC LIMIT ?
        ''', (limit,))
        return [{'log_id': r[0], 'user_id': r[1], 'action': r[2], 'details': r[3], 'timestamp': r[4]} for r in self.cursor.fetchall()]

    def get_all_users(self) -> List[Dict]:
        """Fetch all users for Admin Panel"""
        self.cursor.execute("SELECT user_id, username, email, full_name, age, created_at FROM users")
        return [{'user_id': r[0], 'username': r[1], 'email': r[2], 'full_name': r[3], 'age': r[4], 'created_at': r[5]} for r in self.cursor.fetchall()]
        
    def get_all_careers(self) -> List[Dict]:
        """Fetch all careers from database"""
        self.cursor.execute("SELECT career_id, title, category, description, required_skills, salary_range, growth_prospects FROM career_profiles")
        # Fallback to empty if DB not seeded
        careers = [{'id': r[0], 'title': r[1], 'category': r[2], 'description': r[3], 'skills': r[4].split(',') if r[4] else [], 'salary': r[5], 'growth': r[6]} for r in self.cursor.fetchall()]
        if not careers:
            # Return a much more comprehensive sample data if DB is empty
            return [
                {'title': 'Software Developer', 'category': 'Technology', 'description': 'Builds tech applications and systems.', 'skills': ['Python', 'Java', 'Algorithms', 'Logic'], 'salary': '$80k-120k', 'growth': 'High', 'regional_education': {'USA': 'BS Computer Science, LeetCode', 'India': 'B.Tech CSE, GATE/JEE', 'UK': 'BSc Computer Science'}},
                {'title': 'Data Scientist', 'category': 'Technology', 'description': 'Analyzes and models complex data.', 'skills': ['Math', 'Python', 'Analysis', 'Statistics'], 'salary': '$95k-140k', 'growth': 'High', 'regional_education': {'USA': 'MS Data Science', 'India': 'B.Tech/M.Tech Data Science (IIT/NIT)', 'UK': 'MSc Data Science'}},
                {'title': 'Systems Architect', 'category': 'Technology', 'description': 'Designs IT infrastructure.', 'skills': ['Cloud', 'Design', 'Networking', 'Logic'], 'salary': '$110k-160k', 'growth': 'High', 'regional_education': {'USA': 'AWS Certified Solutions Architect', 'India': 'B.Tech + Cloud Certifications', 'UK': 'Cloud Certifications'}},
                {'title': 'Content Writer', 'category': 'Media', 'description': 'Creates compelling articles and documents.', 'skills': ['Writing', 'Editing', 'Communication'], 'salary': '$50k-80k', 'growth': 'Stable', 'regional_education': {'USA': 'BA English/Journalism', 'India': 'BA/MA English Literature', 'UK': 'BA English'}},
                {'title': 'Journalist', 'category': 'Media', 'description': 'Investigates and reports news stories.', 'skills': ['Investigation', 'Writing', 'Verbal'], 'salary': '$45k-85k', 'growth': 'Medium', 'regional_education': {'USA': 'BA Journalism', 'India': 'BJMC (Bachelor of Journalism)', 'UK': 'NCTJ Diploma'}},
                {'title': 'Teacher', 'category': 'Education', 'description': 'Educates students in specific subjects.', 'skills': ['Communication', 'Patience', 'Empathy', 'Verbal'], 'salary': '$50k-85k', 'growth': 'Stable', 'regional_education': {'USA': 'Degree + State Teaching License', 'India': 'B.Ed (Bachelor of Education) + CTET', 'UK': 'PGCE + QTS'}},
                {'title': 'Accountant', 'category': 'Finance', 'description': 'Manages financial records.', 'skills': ['Math', 'Numeracy', 'Detail-oriented'], 'salary': '$60k-90k', 'growth': 'Stable', 'regional_education': {'USA': 'CPA (Certified Public Accountant)', 'India': 'CA (Chartered Accountant)', 'UK': 'ACCA/CIMA'}},
                {'title': 'Financial Analyst', 'category': 'Finance', 'description': 'Guides investment decisions.', 'skills': ['Analysis', 'Excel', 'Numeracy'], 'salary': '$75k-110k', 'growth': 'High', 'regional_education': {'USA': 'CFA Charterholder', 'India': 'MBA Finance / CFA', 'UK': 'CFA'}},
                {'title': 'Graphic Designer', 'category': 'Arts', 'description': 'Creates visual graphics and branding.', 'skills': ['Creativity', 'Photoshop', 'Visualization'], 'salary': '$50k-90k', 'growth': 'Medium', 'regional_education': {'USA': 'BFA Graphic Design', 'India': 'B.Des (Bachelor of Design) or NID', 'UK': 'BA Graphic Design'}},
                {'title': 'Doctor', 'category': 'Healthcare', 'description': 'Diagnoses and treats patients.', 'skills': ['Biology', 'Empathy', 'Problem Solving'], 'salary': '$150k-300k', 'growth': 'High', 'regional_education': {'USA': 'Pre-Med + MCAT + MD', 'India': 'NEET + MBBS', 'UK': 'UCAT/BMAT + MBChB'}},
                {'title': 'Lawyer', 'category': 'Law', 'description': 'Advises and represents clients in legal matters.', 'skills': ['Argumentation', 'Research', 'Writing'], 'salary': '$90k-200k', 'growth': 'Stable', 'regional_education': {'USA': 'Pre-Law + LSAT + JD', 'India': 'CLAT + LLB', 'UK': 'LNAT + LLB + SQE'}},
            ]
        return careers

    def save_test_result(self, user_id: int, test_type: str, score: float) -> int:
        """Save aptitude test result"""
        self.cursor.execute('''
            INSERT INTO aptitude_tests (user_id, test_type, score)
            VALUES (?, ?, ?)
        ''', (user_id, test_type, score))
        self.conn.commit()
        return self.cursor.lastrowid

    def get_user_test_history(self, user_id: int) -> List[Dict]:
        """Get test history for a user"""
        self.cursor.execute('''
            SELECT test_id, test_type, score, completed_at
            FROM aptitude_tests
            WHERE user_id = ?
            ORDER BY completed_at DESC
        ''', (user_id,))

        results = []
        for row in self.cursor.fetchall():
            results.append({
                'test_id': row[0],
                'test_type': row[1],
                'score': row[2],
                'completed_at': row[3]
            })
        return results

    def close(self):
        """Close database connection"""
        if self.conn:
            self.conn.close()

class AptitudeTestManager:
    """Manage aptitude tests and questions"""

    def __init__(self, db_manager: DatabaseManager):
        self.db = db_manager
        self.load_sample_questions()

    def load_sample_questions(self):
        """Load rich aptitude questions into database (only if not already loaded)"""
        self.db.cursor.execute("SELECT COUNT(*) FROM questions")
        if self.db.cursor.fetchone()[0] >= 25:
            return  # Already loaded, skip to avoid duplicates

        sample_questions = [
            # --- LOGICAL REASONING ---
            {'category': 'logical_reasoning', 'difficulty': 'easy', 'question': 'What comes next: 2, 4, 8, 16, ?', 'options': ['20', '24', '32', '36'], 'correct_answer': 2, 'explanation': 'Each number is multiplied by 2'},
            {'category': 'logical_reasoning', 'difficulty': 'medium', 'question': 'If all roses are flowers and some flowers fade quickly, then:', 'options': ['All roses fade quickly', 'Some roses fade quickly', 'No roses fade quickly', 'Cannot be determined'], 'correct_answer': 3, 'explanation': 'We cannot determine if roses are among the flowers that fade quickly'},
            {'category': 'logical_reasoning', 'difficulty': 'easy', 'question': 'Which number does not belong: 2, 3, 5, 8, 11, 13?', 'options': ['3', '5', '8', '11'], 'correct_answer': 2, 'explanation': '8 is not a prime number; all others are prime'},
            {'category': 'logical_reasoning', 'difficulty': 'hard', 'question': 'All teachers are writers. Some writers are scientists. Therefore:', 'options': ['All teachers are scientists', 'Some teachers are scientists', 'No teachers are scientists', 'Cannot be determined'], 'correct_answer': 3, 'explanation': 'We only know some writers are scientists, not which ones'},
            {'category': 'logical_reasoning', 'difficulty': 'medium', 'question': 'If COLD is coded as DPME, how is WARM coded?', 'options': ['XBSN', 'WBSM', 'XARM', 'XBNS'], 'correct_answer': 0, 'explanation': 'Each letter is shifted by +1 in the alphabet'},
            {'category': 'logical_reasoning', 'difficulty': 'easy', 'question': 'What comes next: 1, 4, 9, 16, 25, ?', 'options': ['30', '36', '49', '42'], 'correct_answer': 1, 'explanation': 'These are perfect squares: 6² = 36'},
            {'category': 'logical_reasoning', 'difficulty': 'medium', 'question': 'A is sister of B. B is brother of C. How is A related to C?', 'options': ['Sister', 'Brother', 'Mother', 'Cannot be determined'], 'correct_answer': 0, 'explanation': 'A is a girl (sister) so she is C\'s sister'},

            # --- NUMERICAL ABILITY ---
            {'category': 'numerical_ability', 'difficulty': 'easy', 'question': 'What is 15% of 200?', 'options': ['20', '25', '30', '35'], 'correct_answer': 2, 'explanation': '15% of 200 = 0.15 × 200 = 30'},
            {'category': 'numerical_ability', 'difficulty': 'medium', 'question': 'A train travels 360 km in 6 hours. What is its average speed?', 'options': ['50 km/h', '60 km/h', '70 km/h', '80 km/h'], 'correct_answer': 1, 'explanation': 'Speed = Distance/Time = 360/6 = 60 km/h'},
            {'category': 'numerical_ability', 'difficulty': 'easy', 'question': 'If a shirt costs $80 and is on 25% sale, what is the price?', 'options': ['$55', '$60', '$65', '$70'], 'correct_answer': 1, 'explanation': '25% of 80 = 20; 80 - 20 = $60'},
            {'category': 'numerical_ability', 'difficulty': 'medium', 'question': 'What is the average of 12, 15, 18, 21, 24?', 'options': ['17', '18', '19', '20'], 'correct_answer': 1, 'explanation': 'Sum = 90; 90 / 5 = 18'},
            {'category': 'numerical_ability', 'difficulty': 'hard', 'question': 'A car depreciates at 20% per year. After 2 years, what % of the original value remains?', 'options': ['60%', '64%', '68%', '72%'], 'correct_answer': 1, 'explanation': '0.8 × 0.8 = 0.64, so 64% remains'},
            {'category': 'numerical_ability', 'difficulty': 'medium', 'question': 'If 6 workers complete a job in 8 days, how many workers do the same job in 4 days?', 'options': ['10', '12', '14', '16'], 'correct_answer': 1, 'explanation': 'Total work = 6 × 8 = 48 units. Workers needed = 48/4 = 12'},

            # --- VERBAL ABILITY ---
            {'category': 'verbal_ability', 'difficulty': 'easy', 'question': 'Choose the correct spelling:', 'options': ['Accomodate', 'Accommodate', 'Acommodate', 'Acomodate'], 'correct_answer': 1, 'explanation': 'The correct spelling is "Accommodate" with double c and double m'},
            {'category': 'verbal_ability', 'difficulty': 'medium', 'question': 'Choose the word most similar to "Eloquent":', 'options': ['Silent', 'Articulate', 'Rude', 'Brief'], 'correct_answer': 1, 'explanation': 'Eloquent means fluent or persuasive in speaking, similar to articulate'},
            {'category': 'verbal_ability', 'difficulty': 'easy', 'question': 'Choose the antonym of "Expand":', 'options': ['Grow', 'Extend', 'Contract', 'Increase'], 'correct_answer': 2, 'explanation': 'Contract means to shrink or reduce, the opposite of expand'},
            {'category': 'verbal_ability', 'difficulty': 'easy', 'question': 'Complete the analogy: Book is to Library as Painting is to ___', 'options': ['Artist', 'Canvas', 'Gallery', 'Museum'], 'correct_answer': 2, 'explanation': 'A gallery is a place where paintings are displayed, just as a library stores books'},
            {'category': 'verbal_ability', 'difficulty': 'medium', 'question': 'Identify the error: "She don\'t like the way he speaks to her."', 'options': ['She', 'don\'t', 'like', 'speaks'], 'correct_answer': 1, 'explanation': 'Should be "doesn\'t" — she is singular, so we use "does not"'},
            {'category': 'verbal_ability', 'difficulty': 'medium', 'question': 'Which is the best synonym for "Meticulous"?', 'options': ['Careless', 'Careful', 'Lazy', 'Hasty'], 'correct_answer': 1, 'explanation': 'Meticulous means showing great attention to detail'},

            # --- SPATIAL REASONING ---
            {'category': 'spatial_reasoning', 'difficulty': 'easy', 'question': 'How many faces does a cube have?', 'options': ['4', '5', '6', '8'], 'correct_answer': 2, 'explanation': 'A cube has 6 faces'},
            {'category': 'spatial_reasoning', 'difficulty': 'medium', 'question': 'If you fold a square piece of paper in half twice, how many layers do you have?', 'options': ['2', '3', '4', '6'], 'correct_answer': 2, 'explanation': 'Each fold doubles layers: 1 → 2 → 4'},
            {'category': 'spatial_reasoning', 'difficulty': 'hard', 'question': 'A 3D shape has 6 faces, 12 edges, and 8 vertices. What is it?', 'options': ['Tetrahedron', 'Cube', 'Pyramid', 'Cylinder'], 'correct_answer': 1, 'explanation': 'A cube (or rectangular prism) has 6 faces, 12 edges, and 8 vertices'},
            {'category': 'spatial_reasoning', 'difficulty': 'medium', 'question': 'Which shape has NO edges and NO vertices?', 'options': ['Cone', 'Cube', 'Sphere', 'Cylinder'], 'correct_answer': 2, 'explanation': 'A sphere is perfectly round with no edges or vertices'},

            # --- ABSTRACT REASONING ---
            {'category': 'abstract_reasoning', 'difficulty': 'medium', 'question': 'Find the pattern: A1, C3, E5, G7, ?', 'options': ['H8', 'I9', 'J10', 'K11'], 'correct_answer': 1, 'explanation': 'Letters skip one (A,C,E,G,I) and numbers increase by 2 (1,3,5,7,9)'},
            {'category': 'abstract_reasoning', 'difficulty': 'easy', 'question': 'What is the next shape in the pattern: Circle, Triangle, Square, Pentagon, ?', 'options': ['Hexagon', 'Octagon', 'Star', 'Rectangle'], 'correct_answer': 0, 'explanation': 'The pattern increases the number of sides: 0, 3, 4, 5, 6 → Hexagon'},
            {'category': 'abstract_reasoning', 'difficulty': 'medium', 'question': 'What comes next: 1, 2, 6, 24, 120, ?', 'options': ['240', '360', '600', '720'], 'correct_answer': 3, 'explanation': 'The pattern is factorials: 1!, 2!, 3!, 4!, 5!, 6! = 720'},
            {'category': 'abstract_reasoning', 'difficulty': 'hard', 'question': 'If → means add, ← means subtract, ↑ means multiply, ↓ means divide. Solve: 5 ↑ 3 → 2 ↓ 17', 'options': ['1', '2', '3', '4'], 'correct_answer': 0, 'explanation': '5 × 3 = 15; 15 + 2 = 17; 17 / 17 = 1'},

            # --- INTERESTS / PREFERENCES (unlabeled, for career mapping) ---
            {'category': 'interest', 'difficulty': 'easy', 'question': 'Which activity do you enjoy most?', 'options': ['Coding and building apps', 'Helping and counseling people', 'Creating art or music', 'Organizing budgets and spreadsheets'], 'correct_answer': -1, 'explanation': 'interest:tech,social,arts,finance'},
            {'category': 'interest', 'difficulty': 'easy', 'question': 'Which describes you best?', 'options': ['I love analyzing data and solving problems', 'I love communicating and leading teams', 'I love designing and crafting things', 'I love teaching and explaining concepts clearly'], 'correct_answer': -1, 'explanation': 'interest:tech,leadership,arts,education'},
            {'category': 'interest', 'difficulty': 'easy', 'question': 'What kind of work environment suits you?', 'options': ['A quiet lab or computer lab', 'A hospital or social center', 'A creative studio or agency', 'A courtroom or business office'], 'correct_answer': -1, 'explanation': 'interest:tech,healthcare,arts,law_business'},
        ]

        for q in sample_questions:
            self.db.cursor.execute('''
                INSERT OR IGNORE INTO questions
                (category, difficulty, question_text, options, correct_answer, explanation)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (q['category'], q['difficulty'], q['question'],
                  json.dumps(q['options']), q['correct_answer'], q['explanation']))

        self.db.conn.commit()


    def get_test_questions(self, categories: List[str] = None,
                          num_questions: int = 10) -> List[Dict]:
        """Get random questions for a test"""

        if categories:
            placeholders = ','.join('?' * len(categories))
            query = f'''
                SELECT question_id, category, difficulty, question_text,
                       options, correct_answer, explanation
                FROM questions
                WHERE category IN ({placeholders})
                ORDER BY RANDOM()
                LIMIT ?
            '''
            self.db.cursor.execute(query, (*categories, num_questions))
        else:
            self.db.cursor.execute('''
                SELECT question_id, category, difficulty, question_text,
                       options, correct_answer, explanation
                FROM questions
                ORDER BY RANDOM()
                LIMIT ?
            ''', (num_questions,))

        questions = []
        for row in self.db.cursor.fetchall():
            questions.append({
                'question_id': row[0],
                'category': row[1],
                'difficulty': row[2],
                'question': row[3],
                'options': json.loads(row[4]),
                'correct_answer': row[5],
                'explanation': row[6]
            })

        return questions

    def evaluate_test(self, user_id: int, test_id: int,
                     responses: List[Dict]) -> Dict:
        """Evaluate test responses and calculate scores"""

        correct_count = 0
        category_scores = {}

        for response in responses:
            is_correct = response['user_answer'] == response['correct_answer']
            if is_correct:
                correct_count += 1

            # Track category-wise performance
            category = response['category']
            if category not in category_scores:
                category_scores[category] = {'correct': 0, 'total': 0}

            category_scores[category]['total'] += 1
            if is_correct:
                category_scores[category]['correct'] += 1

            # Save response to database
            self.db.cursor.execute('''
                INSERT INTO user_responses
                (user_id, test_id, question_id, user_answer, is_correct, time_taken)
                VALUES (?, ?, ?, ?, ?, ?)
            ''', (user_id, test_id, response['question_id'],
                  response['user_answer'], is_correct, response.get('time_taken', 0)))

        self.db.conn.commit()

        # Calculate overall score
        overall_score = (correct_count / len(responses)) * 100

        # Calculate category-wise percentages
        for category in category_scores:
            cat_data = category_scores[category]
            cat_data['percentage'] = (cat_data['correct'] / cat_data['total']) * 100

        return {
            'overall_score': overall_score,
            'correct_answers': correct_count,
            'total_questions': len(responses),
            'category_scores': category_scores
        }

    def generate_career_recommendations(self, user_id: int,
                                      test_results: Dict) -> List[Dict]:
        """Generate career recommendations based on test results with improved logic"""

        recommendations = []
        category_scores = test_results['category_scores']

        # Advanced Career mapping matching aptitudes to job roles
        career_mapping = {
            'logical_reasoning': [
                {'title': 'Software Developer', 'weight': 0.95},
                {'title': 'Data Scientist', 'weight': 0.90},
                {'title': 'Systems Architect', 'weight': 0.85}
            ],
            'verbal_ability': [
                {'title': 'Content Writer', 'weight': 0.95},
                {'title': 'Teacher', 'weight': 0.90},
                {'title': 'Journalist', 'weight': 0.85}
            ],
            'numerical_ability': [
                {'title': 'Accountant', 'weight': 0.95},
                {'title': 'Financial Analyst', 'weight': 0.90},
                {'title': 'Data Scientist', 'weight': 0.80} # Overlapping skills
            ],
            'spatial_reasoning': [
                {'title': 'Architect', 'weight': 0.95},
                {'title': 'Graphic Designer', 'weight': 0.90},
                {'title': 'Systems Architect', 'weight': 0.70}
            ],
            'abstract_reasoning': [
                {'title': 'Research Scientist', 'weight': 0.95},
                {'title': 'Software Developer', 'weight': 0.85},
                {'title': 'Financial Analyst', 'weight': 0.75}
            ]
        }

        # Calculate a unified score for each possible career
        career_scores = {}
        for category, scores in category_scores.items():
            if category in career_mapping:
                percentage = scores['percentage']
                # Grant points to careers linked to this aptitude category proportional to performance
                for job in career_mapping[category]:
                    title = job['title']
                    points_gained = job['weight'] * percentage
                    if title not in career_scores:
                        career_scores[title] = {
                            "total_score": 0, 
                            "reasons": []
                        }
                    career_scores[title]["total_score"] += points_gained
                    if percentage >= 60:
                       career_scores[title]["reasons"].append(f"Strong in {category.replace('_', ' ')}")

        # Normalize logic: top theoretical score would be roughly 2.8 * 100 for Software Dev (appears in Logical, Abstract)
        # So we cap recommendations percentage at 99%.
        for title, data in career_scores.items():
            if data["reasons"]: # Skip jobs with no strong correlating strengths
                normalized_match = min(99.0, data["total_score"] / 1.5) # Divided by general scale factor
                if normalized_match >= 50.0:
                    recommendations.append({
                        'career_title': title,
                        'match_percentage': round(normalized_match, 1),
                        'reasoning': " & ".join(set(data["reasons"]))
                    })

        # Sort recommendations by highest match
        recommendations.sort(key=lambda x: x['match_percentage'], reverse=True)

        # Save Top recommendations to database
        for rec in recommendations[:5]:  
            self.db.cursor.execute('''
                INSERT INTO career_recommendations
                (user_id, career_title, match_percentage, reasoning)
                VALUES (?, ?, ?, ?)
            ''', (user_id, rec['career_title'], rec['match_percentage'], rec['reasoning']))

        self.db.conn.commit()

        return recommendations[:5]

# Testing and demonstration code
def test_database_module():
    """Test the database and testing module"""

    print("="*50)
    print("DATABASE & APTITUDE TESTING MODULE - 40% IMPLEMENTATION")
    print("="*50)

    # Initialize database
    db = DatabaseManager('test_career.db')
    test_manager = AptitudeTestManager(db)

    # Create a test user
    print("\n1. Creating test user...")
    user_id = db.add_user(
        username="test_student",
        email="student@test.com",
        password="password123",
        full_name="Test Student",
        age=17,
        education_level="12th Grade"
    )

    if user_id:
        print(f"   ✓ User created with ID: {user_id}")

    # Authenticate user
    print("\n2. Testing authentication...")
    user = db.authenticate_user("test_student", "password123")
    if user:
        print(f"   ✓ User authenticated: {user['username']}")

    # Get test questions
    print("\n3. Loading aptitude test questions...")
    questions = test_manager.get_test_questions(num_questions=5)
    print(f"   ✓ Loaded {len(questions)} questions")

    # Simulate test responses
    print("\n4. Simulating test responses...")
    test_id = db.save_test_result(user_id, "General Aptitude", 0)

    responses = []
    for i, q in enumerate(questions):
        # Simulate user answering (randomly for demo)
        user_answer = random.randint(0, 3)
        responses.append({
            'question_id': q['question_id'],
            'category': q['category'],
            'user_answer': user_answer,
            'correct_answer': q['correct_answer'],
            'time_taken': random.randint(10, 60)
        })

        print(f"   Q{i+1}: {q['question'][:50]}...")
        print(f"        User answered: Option {user_answer+1}")

    # Evaluate test
    print("\n5. Evaluating test results...")
    results = test_manager.evaluate_test(user_id, test_id, responses)

    print(f"   Overall Score: {results['overall_score']:.1f}%")
    print(f"   Correct Answers: {results['correct_answers']}/{results['total_questions']}")

    print("\n   Category-wise Performance:")
    for category, scores in results['category_scores'].items():
        print(f"   - {category.replace('_', ' ').title()}: {scores['percentage']:.1f}%")

    # Generate recommendations
    print("\n6. Generating career recommendations...")
    recommendations = test_manager.generate_career_recommendations(user_id, results)

    print("   Top Career Recommendations:")
    for i, rec in enumerate(recommendations, 1):
        print(f"   {i}. {rec['career_title']} (Match: {rec['match_percentage']:.1f}%)")
        print(f"      Reason: {rec['reasoning']}")

    # Get test history
    print("\n7. Retrieving test history...")
    history = db.get_user_test_history(user_id)
if __name__ == "__main__":
    test_database_module() # Indented with 4 spaces

