# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14t-q0hpvT1RmTYPxLVMyUIYuJSXVntYA
"""

# app.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from agarwalwork import DatabaseManager, AptitudeTestManager
from sanyamwork import PersonalityAnalyzer
import json
import random

# --- INITIALIZATION ---
app = Flask(__name__)
# CORS allows the React frontend to communicate with this backend
CORS(app)

# Initialize your backend modules
db_manager = DatabaseManager('career_counseling.db')
aptitude_manager = AptitudeTestManager(db_manager)
personality_analyzer = PersonalityAnalyzer()
print("Backend server initialized successfully!")

# Global error handler to log errors
@app.errorhandler(Exception)
def handle_exception(e):
    # Log the error if it's not a standard HTTP error
    db_manager.log_error(str(e), endpoint=request.path)
    return jsonify({"error": "An internal error occurred."}), 500

# Function to log regular user actions
@app.after_request
def log_request_activity(response):
    if request.path.startswith('/aptitude-test/submit') and response.status_code == 200:
        # User ID is hardcoded to 1 for now in the frontend
        db_manager.log_activity(1, 'SUBMITTED_TEST', 'User finished aptitude test')
    elif request.path.startswith('/analyze-essay') and response.status_code == 200:
        db_manager.log_activity(1, 'ANALYZED_ESSAY', 'User analyzed personal essay')
    return response

# --- API ENDPOINTS ---
@app.route('/')
def index():
    return "Career Counseling Backend is running!"

@app.route('/aptitude-test/questions', methods=['GET'])
def get_questions():
    """Endpoint to get questions for the aptitude test"""
    try:
        questions = aptitude_manager.get_test_questions(num_questions=8)
        # We don't send the correct answer to the client
        for q in questions:
            del q['correct_answer']
            del q['explanation']
        return jsonify(questions)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/aptitude-test/submit', methods=['POST'])
def submit_test():
    """Endpoint to submit test answers and get results"""
    try:
        data = request.json
        user_id = data.get('user_id', 1)  # Using a default user_id=1 for now
        user_responses = data.get('answers')

        all_questions_in_db = aptitude_manager.get_test_questions(num_questions=100)
        full_questions_map = {q['question_id']: q for q in all_questions_in_db}

        eval_responses = []
        for res in user_responses:
            question_id = res['question_id']
            if question_id in full_questions_map:
                question_data = full_questions_map[question_id]
                eval_responses.append({
                    'question_id': question_id,
                    'category': question_data['category'],
                    'user_answer': res['user_answer'],
                    'correct_answer': question_data['correct_answer']
                })

        test_id = db_manager.save_test_result(user_id, "General Aptitude", 0)
        results = aptitude_manager.evaluate_test(user_id, test_id, eval_responses)
        recommendations = aptitude_manager.generate_career_recommendations(user_id, results)

        return jsonify({"results": results, "recommendations": recommendations})
    except Exception as e:
        print(f"Error submitting test: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/careers', methods=['GET'])
def get_careers():
    """Endpoint to get all career profiles for the explorer page"""
    try:
        careers = db_manager.get_all_careers()
        career_explorer_data = {}
        for career in careers:
            category = career.get('category', 'General').capitalize()
            if category not in career_explorer_data:
                career_explorer_data[category] = []
            career_explorer_data[category].append(career)
        return jsonify(career_explorer_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/analyze-essay', methods=['POST'])
def analyze_essay():
    """Endpoint for NLP-based essay analysis"""
    try:
        data = request.json
        essay_text = data.get('essay')
        if not essay_text:
            return jsonify({"error": "Essay text is required"}), 400
        analysis = personality_analyzer.analyze_career_essay(essay_text)
        return jsonify(analysis)
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/analyze-essay')
        return jsonify({"error": str(e)}), 500

@app.route('/recommendations/feedback', methods=['POST'])
def submit_feedback():
    """Endpoint to record user feedback (upvote/downvote)"""
    try:
        data = request.json
        user_id = data.get('user_id', 1)
        rec_id = data.get('recommendation_id')
        feedback_type = data.get('feedback_type') # 'UPVOTE' or 'DOWNVOTE'
        if not rec_id or not feedback_type:
             return jsonify({"error": "Missing parameters"}), 400
        
        db_manager.add_recommendation_feedback(user_id, rec_id, feedback_type)
        return jsonify({"status": "success"})
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/recommendations/feedback')
        return jsonify({"error": str(e)}), 500

@app.route('/market-insights', methods=['GET'])
def get_market_insights():
    """Simulate realistic localized market data based on career and location"""
    career = request.args.get('career', 'Professional')
    location = request.args.get('location', 'USA')
    
    # Generate random localized data
    if location == 'India':
        salary_min = random.randint(3, 15)
        salary_max = salary_min + random.randint(2, 10)
        salary_str = f"₹{salary_min}L - ₹{salary_max}L / yr"
        locations_list = ["Bangalore", "Mumbai", "Delhi NCR", "Hyderabad", "Pune"]
    elif location == 'UK':
        salary_min = random.randint(25, 60)
        salary_max = salary_min + random.randint(10, 40)
        salary_str = f"£{salary_min}k - £{salary_max}k / yr"
        locations_list = ["London", "Manchester", "Birmingham", "Edinburgh"]
    else:  # Default USA
        salary_min = random.randint(50, 110)
        salary_max = salary_min + random.randint(20, 60)
        salary_str = f"${salary_min}k - ${salary_max}k / yr"
        locations_list = ["New York, NY", "San Francisco, CA", "Austin, TX", "Seattle, WA", "Remote"]
        
    num_openings = random.randint(120, 5000)
    demand = random.choice(["Very High", "High", "Stable", "Growing"])
    
    # Generate fake job listings
    job_listings = []
    for _ in range(random.randint(2, 4)):
        company = random.choice(["TechFlow", "Global Systems Inc", "Apex Solutions", "Innovative Corp", "NextGen Partners", "Pioneer LLC"])
        job_listings.append({
            "title": career,
            "company": company,
            "location": random.choice(locations_list),
            "posted": f"{random.randint(1, 14)} days ago"
        })
        
    return jsonify({
        "career": career,
        "location": location,
        "average_salary_range": salary_str,
        "active_openings": num_openings,
        "demand_trend": demand,
        "live_jobs": job_listings
    })

# --- ADMIN ENDPOINTS ---
@app.route('/admin/login', methods=['POST'])
def admin_login():
    data = request.json
    username = data.get('username')
    password = data.get('password')
    if db_manager.authenticate_admin(username, password):
        return jsonify({"status": "success", "token": "fake-jwt-token-for-demo"})
    return jsonify({"error": "Invalid credentials"}), 401

@app.route('/admin/dashboard-stats', methods=['GET'])
def admin_stats():
    # In a real app, verify token here
    try:
        stats = db_manager.get_dashboard_stats()
        return jsonify(stats)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/admin/users', methods=['GET'])
def admin_users():
    try:
        users = db_manager.get_all_users()
        return jsonify(users)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/admin/logs', methods=['GET'])
def admin_logs():
    try:
        limit = request.args.get('limit', 50, type=int)
        logs = db_manager.get_recent_activity(limit)
        return jsonify(logs)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# --- RUN THE SERVER ---
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True, use_reloader=False, threaded=False)