# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14t-q0hpvT1RmTYPxLVMyUIYuJSXVntYA
"""

# app.py
from flask import Flask, request, jsonify
from flask_cors import CORS
from agarwalwork import DatabaseManager, AptitudeTestManager
from sanyamwork import PersonalityAnalyzer, get_gemini_client
import json
import random
import os
from dotenv import load_dotenv
from google.genai import types

load_dotenv()

# --- INITIALIZATION ---
app = Flask(__name__)
# CORS allows the React frontend to communicate with this backend
CORS(app, supports_credentials=True, resources={r"/*": {"origins": "*"}})

# Initialize your backend modules
db_manager = DatabaseManager('career_counseling.db')
aptitude_manager = AptitudeTestManager(db_manager)
personality_analyzer = PersonalityAnalyzer()
print("Backend server initialized successfully!")

# Global error handler to log errors
@app.errorhandler(Exception)
def handle_exception(e):
    # Log the error if it's not a standard HTTP error
    db_manager.log_error(str(e), endpoint=request.path)
    return jsonify({"error": "An internal error occurred."}), 500

# Function to log regular user actions
@app.after_request
def log_request_activity(response):
    if request.path.startswith('/aptitude-test/submit') and response.status_code == 200:
        # User ID is hardcoded to 1 for now in the frontend
        db_manager.log_activity(1, 'SUBMITTED_TEST', 'User finished aptitude test')
    elif request.path.startswith('/analyze-essay') and response.status_code == 200:
        db_manager.log_activity(1, 'ANALYZED_ESSAY', 'User analyzed personal essay')
    return response

# --- API ENDPOINTS ---
@app.route('/')
def index():
    return "Career Counseling Backend is running!"

@app.route('/aptitude-test/questions', methods=['GET'])
def get_questions():
    """Endpoint to get questions for the aptitude test - 15 questions"""
    try:
        # Get a mix of aptitude and interest questions
        aptitude_qs = aptitude_manager.get_test_questions(
            categories=['logical_reasoning', 'numerical_ability', 'verbal_ability', 'spatial_reasoning', 'abstract_reasoning'],
            num_questions=12
        )
        interest_qs = aptitude_manager.get_test_questions(
            categories=['interest'],
            num_questions=3
        )
        questions = aptitude_qs + interest_qs
        for q in questions:
            del q['correct_answer']
            del q['explanation']
        return jsonify(questions)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/aptitude-test/submit', methods=['POST'])
def submit_test():
    """Endpoint to submit test answers and get results"""
    try:
        data = request.json
        user_id = data.get('user_id', 1)
        user_responses = data.get('answers')
        user_age = data.get('age', 'Not provided')
        user_education = data.get('education', 'Not provided')
        user_interests = data.get('interests', [])  # interest question answers

        all_questions_in_db = aptitude_manager.get_test_questions(num_questions=200)
        full_questions_map = {q['question_id']: q for q in all_questions_in_db}

        eval_responses = []
        interest_responses = []
        for res in user_responses:
            question_id = res['question_id']
            if question_id in full_questions_map:
                question_data = full_questions_map[question_id]
                if question_data['category'] == 'interest':
                    interest_responses.append({'option': res.get('user_answer'), 'explanation': question_data.get('explanation', '')})
                else:
                    eval_responses.append({
                        'question_id': question_id,
                        'category': question_data['category'],
                        'user_answer': res['user_answer'],
                        'correct_answer': question_data['correct_answer']
                    })

        test_id = db_manager.save_test_result(user_id, "General Aptitude", 0)
        results = aptitude_manager.evaluate_test(user_id, test_id, eval_responses) if eval_responses else {'overall_score': 0, 'category_scores': {}, 'correct_answers': 0, 'total_questions': 0}
        
        # Use rule-based recommendations as fallback
        recommendations = aptitude_manager.generate_career_recommendations(user_id, results)
        
        return jsonify({
            "results": results, 
            "recommendations": recommendations,
            "user_context": {"age": user_age, "education": user_education, "interests": interest_responses}
        })
    except Exception as e:
        print(f"Error submitting test: {e}")
        return jsonify({"error": str(e)}), 500


@app.route('/smart-recommendations', methods=['POST'])
def smart_recommendations():
    """Use Gemini AI to generate highly personalized career recommendations based on user profile + test scores."""
    try:
        data = request.json
        age = data.get('age', 'unknown')
        education = data.get('education', 'unspecified')
        location = data.get('location', 'USA')
        category_scores = data.get('category_scores', {})
        interest_answers = data.get('interest_answers', [])

        client = get_gemini_client()
        if not client:
            return jsonify({"error": "Gemini API key not configured"}), 500

        # Build skill summary string
        skills_str = ", ".join([f"{k.replace('_', ' ')}: {round(v.get('percentage', 0))}%" for k, v in category_scores.items() if isinstance(v, dict)]) or "No aptitude scores available"
        interests_str = ", ".join([r['option_text'] for r in interest_answers if 'option_text' in r]) or "Not provided"

        prompt = f"""You are an expert career counselor. Analyze this user profile and provide 5 highly personalized career recommendations.

User Profile:
- Age: {age}
- Education: {education}
- Location: {location}
- Aptitude Scores: {skills_str}
- Stated Interests: {interests_str}

For each career recommendation, respond ONLY with a JSON array of 5 objects. Each object must have:
- "career_title": specific job title
- "match_percentage": a number 60-99 based on how well it fits
- "reasoning": one clear sentence explaining why this career fits THIS specific user based on their age, education, and scores
- "next_step": one concrete action they can take THIS WEEK to get started

Return ONLY the raw JSON array, no explanation, no markdown."""

        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
            config=types.GenerateContentConfig(
                temperature=0.4,
                max_output_tokens=1024,
                response_mime_type="application/json"
            )
        )
        
        raw = response.text.strip()
        if raw.startswith('```'):
            raw = raw.split('```')[1]
            if raw.startswith('json'): raw = raw[4:]
            raw = raw.strip()
        
        recs = json.loads(raw)
        return jsonify({"recommendations": recs})
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/smart-recommendations')
        print(f"Smart recommendations error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/careers', methods=['GET'])
def get_careers():
    """Endpoint to get all career profiles for the explorer page"""
    try:
        careers = db_manager.get_all_careers()
        career_explorer_data = {}
        for career in careers:
            category = career.get('category', 'General').capitalize()
            if category not in career_explorer_data:
                career_explorer_data[category] = []
            career_explorer_data[category].append(career)
        return jsonify(career_explorer_data)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/analyze-essay', methods=['POST'])
def analyze_essay():
    """Endpoint for NLP-based essay analysis"""
    try:
        data = request.json
        essay_text = data.get('essay')
        if not essay_text:
            return jsonify({"error": "Essay text is required"}), 400
        analysis = personality_analyzer.analyze_career_essay(essay_text)
        return jsonify(analysis)
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/analyze-essay')
        return jsonify({"error": str(e)}), 500

@app.route('/generate-roadmap', methods=['POST'])
def generate_roadmap():
    """Endpoint to generate an AI Career Roadmap using Gemini"""
    try:
        data = request.json
        career_title = data.get('career')
        user_location = data.get('location', 'Global')
        user_age = data.get('age', 'unknown')
        user_education = data.get('education', 'unspecified')
        
        if not career_title:
            return jsonify({"error": "Career title is required"}), 400
        
        client = get_gemini_client()
        if not client:
            return jsonify({"roadmap": f"# Roadmap for {career_title}\n\nPlease add a Google Gemini API Key to see the AI generated roadmap."})
        
        prompt = f"""Create a personalized, step-by-step 12-month career roadmap for someone who wants to become a '{career_title}'.
        
        User context:
        - Age: {user_age}
        - Education: {user_education}
        - Location: {user_location}
        
        Format the response in clean Markdown with three sections:
        ## 🌱 Months 1-3: Foundation Building
        ## 🚀 Months 4-6: Skill Development
        ## 🎯 Months 7-12: Job Hunting & Launch
        
        In each section, give 3-4 concrete, actionable steps tailored to the user's age, background, and location. Be specific about courses, certifications, and projects to build."""
        
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=prompt,
            config=types.GenerateContentConfig(temperature=0.5, max_output_tokens=2048)
        )
        return jsonify({"roadmap": response.text})
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/generate-roadmap')
        return jsonify({"error": str(e)}), 500

@app.route('/chat-coach', methods=['POST'])
def chat_coach():
    """Endpoint for the Interactive AI Career Coach Chatbot"""
    try:
        data = request.json
        messages = data.get('messages', [])
        
        if not messages:
            return jsonify({"error": "Messages array is required"}), 400
        
        client = get_gemini_client()
        if not client:
            return jsonify({"reply": "I'm the AI Career Coach, but my Gemini API key is missing. Please add it to get started!"})
        
        # Build the full conversation context as a single prompt for simplicity and reliability
        system = "You are CareerAI Coach, a professional, encouraging, and knowledgeable career counselor. Keep your responses concise (2-3 paragraphs max), actionable, and warm. Use bullet points where helpful."
 
        history_text = f"[SYSTEM INSTRUCTIONS]: {system}\n\n"
        for msg in messages:
            role = "User" if msg['role'] == 'user' else "CareerAI Coach"
            history_text += f"{role}: {msg['content']}\n\n"
        
        history_text += "CareerAI Coach:"
        
        response = client.models.generate_content(
            model="gemini-2.0-flash",
            contents=history_text,
            config=types.GenerateContentConfig(temperature=0.7, max_output_tokens=1024)
        )
        return jsonify({"reply": response.text.strip()})
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/chat-coach')
        print(f"Chat-coach error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/recommendations/feedback', methods=['POST'])
def submit_feedback():
    """Endpoint to record user feedback (upvote/downvote)"""
    try:
        data = request.json
        user_id = data.get('user_id', 1)
        rec_id = data.get('recommendation_id')
        feedback_type = data.get('feedback_type') # 'UPVOTE' or 'DOWNVOTE'
        if not rec_id or not feedback_type:
             return jsonify({"error": "Missing parameters"}), 400
        
        db_manager.add_recommendation_feedback(user_id, rec_id, feedback_type)
        return jsonify({"status": "success"})
    except Exception as e:
        db_manager.log_error(str(e), endpoint='/recommendations/feedback')
        return jsonify({"error": str(e)}), 500

@app.route('/market-insights', methods=['GET'])
def get_market_insights():
    """Simulate realistic localized market data based on career and location"""
    career = request.args.get('career', 'Professional')
    location = request.args.get('location', 'USA')
    
    # Generate random localized data
    if location == 'India':
        salary_min = random.randint(3, 15)
        salary_max = salary_min + random.randint(2, 10)
        salary_str = f"₹{salary_min}L - ₹{salary_max}L / yr"
        locations_list = ["Bangalore", "Mumbai", "Delhi NCR", "Hyderabad", "Pune"]
    elif location == 'UK':
        salary_min = random.randint(25, 60)
        salary_max = salary_min + random.randint(10, 40)
        salary_str = f"£{salary_min}k - £{salary_max}k / yr"
        locations_list = ["London", "Manchester", "Birmingham", "Edinburgh"]
    else:  # Default USA
        salary_min = random.randint(50, 110)
        salary_max = salary_min + random.randint(20, 60)
        salary_str = f"${salary_min}k - ${salary_max}k / yr"
        locations_list = ["New York, NY", "San Francisco, CA", "Austin, TX", "Seattle, WA", "Remote"]
        
    num_openings = random.randint(120, 5000)
    demand = random.choice(["Very High", "High", "Stable", "Growing"])
    
    # Generate fake job listings
    job_listings = []
    for _ in range(random.randint(2, 4)):
        company = random.choice(["TechFlow", "Global Systems Inc", "Apex Solutions", "Innovative Corp", "NextGen Partners", "Pioneer LLC"])
        job_listings.append({
            "title": career,
            "company": company,
            "location": random.choice(locations_list),
            "posted": f"{random.randint(1, 14)} days ago"
        })
        
    return jsonify({
        "career": career,
        "location": location,
        "average_salary_range": salary_str,
        "active_openings": num_openings,
        "demand_trend": demand,
        "live_jobs": job_listings
    })

# --- ADMIN ENDPOINTS ---
@app.route('/admin/login', methods=['POST'])
def admin_login():
    data = request.json
    username = data.get('username')
    password = data.get('password')
    if db_manager.authenticate_admin(username, password):
        return jsonify({"status": "success", "token": "fake-jwt-token-for-demo"})
    return jsonify({"error": "Invalid credentials"}), 401

@app.route('/admin/dashboard-stats', methods=['GET'])
def admin_stats():
    # In a real app, verify token here
    try:
        stats = db_manager.get_dashboard_stats()
        return jsonify(stats)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/admin/users', methods=['GET'])
def admin_users():
    try:
        users = db_manager.get_all_users()
        return jsonify(users)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/admin/logs', methods=['GET'])
def admin_logs():
    try:
        limit = request.args.get('limit', 50, type=int)
        logs = db_manager.get_recent_activity(limit)
        return jsonify(logs)
    except Exception as e:
        return jsonify({"error": str(e)}), 500

# --- RUN THE SERVER ---
if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True, use_reloader=False, threaded=False)