# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc79NoFgyM2t8cLgA9WxtyjUSx9t14fv
"""

# -*- coding: utf-8 -*-
# NLP CAREER COUNSELING MODULE - SANYAM JAIN

import pandas as pd
import numpy as np
import google.generativeai as genai
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import re
from typing import Dict, List
import json
import os

# Download required NLTK data if not present
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except nltk.downloader.DownloadError:
    nltk.download('vader_lexicon')

class PersonalityAnalyzer:
    """NLP-based personality and interest analyzer"""

    def __init__(self):
        # Initialize sentiment analyzer (keep local for speed/free polarity)
        self.sia = SentimentIntensityAnalyzer()
        
        # Initialize Google Gemini
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            print("WARNING: GEMINI_API_KEY environment variable not set. Essay analysis will fail.")
        else:
            genai.configure(api_key=api_key)
            
        # Optional: You can specify a particular Gemini model, like gemini-pro
        self.generation_config = {
            "temperature": 0.4, # Lower temperature for more consistent, structured JSON responses
            "top_p": 0.95,
            "top_k": 40,
            "max_output_tokens": 8192,
            "response_mime_type": "application/json",
        }
            
        # Career categories and traits still useful for reference/prompting
        self.career_categories = [
            "Technology and Engineering", "Healthcare and Medicine", "Business and Finance",
            "Arts and Design", "Education and Teaching", "Science and Research",
            "Law and Public Service", "Media and Communication", "Social Work and Counseling"
        ]
        self.personality_traits = [
            "analytical", "creative", "social", "leadership", "detail oriented", "adaptable"
        ]

    def analyze_career_essay(self, essay: str) -> Dict:
        """Complete analysis of career essay/statement using LLM"""
        if not essay or len(essay.strip()) == 0:
            raise ValueError("Essay text cannot be empty.")
            
        # Keep basic sentiment local - it's fast and easy
        sentiment = self.sia.polarity_scores(essay)
        
        # If API key is missing, return fallback
        if not os.environ.get("GEMINI_API_KEY"):
             return {
                'sentiment': {'positive': round(sentiment['pos'], 2), 'neutral': round(sentiment['neu'], 2), 'negative': round(sentiment['neg'], 2)},
                'top_interests': {"Technology and Engineering": 0.6, "Business and Finance": 0.4},
                'personality_traits': {'analytical': 0.8, 'adaptable': 0.6},
                'career_recommendations': ["Software Developer", "Data Scientist", "Financial Analyst"]
            }

        try:
            model = genai.GenerativeModel(
                model_name="gemini-1.5-flash", # Use standard fast model
                generation_config=self.generation_config
            )

            prompt = f"""
            Analyze the following essay written by a user looking for career guidance.
            Based strictly on the content and tone of their essay, generate a JSON response with exactly three keys:
            
            1. "top_interests": An object mapping the top 2-3 most relevant career categories (from the list below) to a confidence score between 0.0 and 1.0.
            2. "personality_traits": An object mapping the top 3-4 detected personality traits to a confidence score between 0.0 and 1.0 (e.g. {{"analytical": 0.85, "creative": 0.70}}). Use lowercase with underscores for multi-word traits (e.g., detail_oriented).
            3. "career_recommendations": An array of exactly 5 specific job titles that perfectly suit the user's analyzed interests and traits.
            
            Valid Career Categories: {', '.join(self.career_categories)}
            Suggested Personality Traits (you can use others if highly relevant): {', '.join(self.personality_traits)}
            
            Essay to Analyze:
            "{essay}"
            """

            response = model.generate_content(prompt)
            # Since we requested application/json, response.text should be parseable JSON
            json_response = response.text
            
            # Sometimes models wrap JSON in markdown blocks even when told not to, so we clean it.
            if json_response.startswith("```json"):
                json_response = json_response[7:-3]
            elif json_response.startswith("```"):
                json_response = json_response[3:-3]
                
            analysis_data = json.loads(json_response.strip())
            
            return {
                'sentiment': {'positive': round(sentiment['pos'], 2), 'neutral': round(sentiment['neu'], 2), 'negative': round(sentiment['neg'], 2)},
                'top_interests': analysis_data.get('top_interests', {}),
                'personality_traits': analysis_data.get('personality_traits', {}),
                'career_recommendations': analysis_data.get('career_recommendations', [])
            }

        except Exception as e:
            print(f"Error calling Gemini API: {e}")
            # Fallback if Gemini fails
            return {
                'sentiment': {'positive': round(sentiment['pos'], 2), 'neutral': round(sentiment['neu'], 2), 'negative': round(sentiment['neg'], 2)},
                'top_interests': {"Technology and Engineering": 0.5},
                'personality_traits': {'adaptable': 0.5},
                'career_recommendations': ["General Consultant"]
            }

    def generate_recommendations(self, interests: Dict, traits: Dict) -> List:
        """Generate career recommendations based on analysis"""
        career_mapping = {
            "Technology and Engineering": ["Software Developer", "Data Scientist", "AI Engineer"],
            "Healthcare and Medicine": ["Doctor", "Nurse", "Medical Researcher"],
            "Business and Finance": ["Financial Analyst", "Marketing Manager", "Entrepreneur"],
            "Arts and Design": ["Graphic Designer", "UI/UX Designer", "Animator"],
            "Education and Teaching": ["Teacher", "Professor", "Educational Counselor"]
        }
        recommendations = []
        for category, score in list(interests.items())[:2]:
            if category in career_mapping:
                recommendations.extend(career_mapping[category][:3])
        return recommendations[:5]