# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc79NoFgyM2t8cLgA9WxtyjUSx9t14fv
"""

# -*- coding: utf-8 -*-
# NLP CAREER COUNSELING MODULE - SANYAM JAIN

import pandas as pd
import numpy as np
from transformers import pipeline
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import re
from typing import Dict, List
import json

# Download required NLTK data if not present
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except nltk.downloader.DownloadError:
    nltk.download('vader_lexicon')

class PersonalityAnalyzer:
    """NLP-based personality and interest analyzer"""

    def __init__(self):
        # Initialize sentiment analyzer
        self.sia = SentimentIntensityAnalyzer()
        # Initialize zero-shot classification for interests
        # Upgraded to mDeBERTa to support zero-shot classification in 100+ languages natively without tokenizer crashes
        self.classifier = pipeline("zero-shot-classification", model="MoritzLaurer/mDeBERTa-v3-base-mnli-xnli")
        # Career categories for classification
        self.career_categories = [
            "Technology and Engineering", "Healthcare and Medicine", "Business and Finance",
            "Arts and Design", "Education and Teaching", "Science and Research",
            "Law and Public Service", "Media and Communication", "Social Work and Counseling"
        ]
        # Personality basic traits for linguistic processing (multilingual compatible)
        self.personality_traits = [
            "analytical", "creative", "social", "leadership", "detail oriented", "adaptable"
        ]

    def analyze_text_interests(self, text: str) -> Dict:
        """Analyze user's interests from their text input"""
        try:
            result = self.classifier(text, self.career_categories)
            top_interests = {}
            for i in range(min(3, len(result['labels']))):
                top_interests[result['labels'][i]] = round(result['scores'][i], 3)
            return top_interests
        except Exception as e:
            print(f"Warning: Zero-shot classification failed. {e}")
            # Fallback for when the model fails or is unavailable
            return {
                "Technology and Engineering": 0.45,
                "Business and Finance": 0.30,
                "Arts and Design": 0.25
            }

    def extract_personality_traits(self, text: str) -> Dict:
        """Extract personality traits from text using zero-shot classification for multilingual support"""
        try:
            result = self.classifier(text, self.personality_traits)
            trait_scores = {}
            for i in range(len(result['labels'])):
                # Normalize keys (e.g. "detail oriented" -> "detail_oriented")
                key = result['labels'][i].replace(" ", "_")
                trait_scores[key] = round(result['scores'][i], 3)
            
            # Normalize to strong traits
            if trait_scores:
                max_score = max(trait_scores.values())
                if max_score > 0:
                    trait_scores = {k: min(1.0, round((v / max_score) * 1.2, 2)) for k, v in trait_scores.items() if (v / max_score) > 0.4}
            else:
                trait_scores = {'adaptable': 0.60, 'social': 0.50}
                
            return trait_scores
        except Exception as e:
            print(f"Warning: Zero-shot trait classification failed. {e}")
            return {'adaptable': 0.60, 'collaborative': 0.50}

    def analyze_career_essay(self, essay: str) -> Dict:
        """Complete analysis of career essay/statement"""
        if not essay or len(essay.strip()) == 0:
            raise ValueError("Essay text cannot be empty.")
            
        sentiment = self.sia.polarity_scores(essay)
        interests = self.analyze_text_interests(essay)
        traits = self.extract_personality_traits(essay)
        recommendations = self.generate_recommendations(interests, traits)
        return {
            'sentiment': {'positive': round(sentiment['pos'], 2), 'neutral': round(sentiment['neu'], 2), 'negative': round(sentiment['neg'], 2)},
            'top_interests': interests,
            'personality_traits': traits,
            'career_recommendations': recommendations
        }

    def generate_recommendations(self, interests: Dict, traits: Dict) -> List:
        """Generate career recommendations based on analysis"""
        career_mapping = {
            "Technology and Engineering": ["Software Developer", "Data Scientist", "AI Engineer"],
            "Healthcare and Medicine": ["Doctor", "Nurse", "Medical Researcher"],
            "Business and Finance": ["Financial Analyst", "Marketing Manager", "Entrepreneur"],
            "Arts and Design": ["Graphic Designer", "UI/UX Designer", "Animator"],
            "Education and Teaching": ["Teacher", "Professor", "Educational Counselor"]
        }
        recommendations = []
        for category, score in list(interests.items())[:2]:
            if category in career_mapping:
                recommendations.extend(career_mapping[category][:3])
        return recommendations[:5]