# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qc79NoFgyM2t8cLgA9WxtyjUSx9t14fv
"""

# -*- coding: utf-8 -*-
# NLP CAREER COUNSELING MODULE - SANYAM JAIN

import pandas as pd
import numpy as np
from transformers import pipeline
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer
import re
from typing import Dict, List
import json

# Download required NLTK data if not present
try:
    nltk.data.find('sentiment/vader_lexicon.zip')
except nltk.downloader.DownloadError:
    nltk.download('vader_lexicon')

class PersonalityAnalyzer:
    """NLP-based personality and interest analyzer"""

    def __init__(self):
        # Initialize sentiment analyzer
        self.sia = SentimentIntensityAnalyzer()
        # Initialize zero-shot classification for interests
        self.classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")
        # Career categories for classification
        self.career_categories = [
            "Technology and Engineering", "Healthcare and Medicine", "Business and Finance",
            "Arts and Design", "Education and Teaching", "Science and Research",
            "Law and Public Service", "Media and Communication", "Social Work and Counseling"
        ]
        # Personality traits mapping
        self.personality_traits = {
            'analytical': ['analyze', 'solve', 'think', 'logic', 'data', 'research'],
            'creative': ['create', 'design', 'imagine', 'art', 'innovate', 'build'],
            'social': ['help', 'teach', 'care', 'communicate', 'team', 'collaborate'],
            'leadership': ['lead', 'manage', 'organize', 'decide', 'responsible'],
            'detail_oriented': ['detail', 'precise', 'accurate', 'careful', 'thorough']
        }

    def analyze_text_interests(self, text: str) -> Dict:
        """Analyze user's interests from their text input"""
        result = self.classifier(text, self.career_categories)
        top_interests = {}
        for i in range(min(3, len(result['labels']))):
            top_interests[result['labels'][i]] = round(result['scores'][i], 3)
        return top_interests

    def extract_personality_traits(self, text: str) -> Dict:
        """Extract personality traits from text"""
        text_lower = text.lower()
        trait_scores = {}
        for trait, keywords in self.personality_traits.items():
            score = sum(1 for keyword in keywords if keyword in text_lower)
            if score > 0:
                trait_scores[trait] = score
        if trait_scores:
            max_score = max(trait_scores.values())
            trait_scores = {k: round(v / max_score, 2) for k, v in trait_scores.items()}
        return trait_scores

    def analyze_career_essay(self, essay: str) -> Dict:
        """Complete analysis of career essay/statement"""
        sentiment = self.sia.polarity_scores(essay)
        interests = self.analyze_text_interests(essay)
        traits = self.extract_personality_traits(essay)
        recommendations = self.generate_recommendations(interests, traits)
        return {
            'sentiment': {'positive': round(sentiment['pos'], 2), 'neutral': round(sentiment['neu'], 2), 'negative': round(sentiment['neg'], 2)},
            'top_interests': interests,
            'personality_traits': traits,
            'career_recommendations': recommendations
        }

    def generate_recommendations(self, interests: Dict, traits: Dict) -> List:
        """Generate career recommendations based on analysis"""
        career_mapping = {
            "Technology and Engineering": ["Software Developer", "Data Scientist", "AI Engineer"],
            "Healthcare and Medicine": ["Doctor", "Nurse", "Medical Researcher"],
            "Business and Finance": ["Financial Analyst", "Marketing Manager", "Entrepreneur"],
            "Arts and Design": ["Graphic Designer", "UI/UX Designer", "Animator"],
            "Education and Teaching": ["Teacher", "Professor", "Educational Counselor"]
        }
        recommendations = []
        for category, score in list(interests.items())[:2]:
            if category in career_mapping:
                recommendations.extend(career_mapping[category][:3])
        return recommendations[:5]